# Generated by Django 2.0.1 on 2018-01-28 05:34

from django.db import migrations, models
import django.db.models.deletion
import tariffs.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations_jp', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(db_index=True, editable=False)),
                ('zipcode', models.CharField(blank=True, db_index=True, default=None, max_length=10, null=True)),
                ('charge', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Distination Charge')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_jp.City')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['package', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(db_index=True, editable=False)),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('default_charge', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Default Charge')),
                ('delegate_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_by', to='tariffs.Package')),
                ('mixes', models.ManyToManyField(blank=True, to='tariffs.Package')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['tariff', 'seq'],
            },
            bases=(models.Model, tariffs.methods.Package),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
            bases=(models.Model, tariffs.methods.Tariff),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'proxy': True,
                'indexes': [],
            },
            bases=('locations_jp.jpaddress',),
        ),
        migrations.AddField(
            model_name='package',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.Tariff'),
        ),
        migrations.AddField(
            model_name='charge',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.Package'),
        ),
        migrations.AddField(
            model_name='charge',
            name='prefecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations_jp.Prefecture'),
        ),
    ]
