# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('time_from', models.TimeField(blank=True, default=None, null=True)),
                ('time_to', models.TimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['time_from'],
            },
        ),
    ]
