# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='can_mix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='free_limit',
            field=models.DecimalField(decimal_places=0, default=1000000, max_digits=8, verbose_name='Free Limit'),
        ),
    ]
